#!/bin/bash

Sink='alsa_output.pci-0000_00_1b.0.analog-stereo'
Source='alsa_input.pci-0000_00_1b.0.analog-stereo'

if [ $# -eq 0 ]; then
    pactl load-module module-null-sink sink_name=Virtual1
    pactl load-module module-null-sink sink_name=Virtual2

    pactl load-module module-loopback source=$Source sink=Virtual1
    pactl load-module module-loopback source=Virtual2.monitor sink=Virtual1
  
    pactl load-module module-loopback source=Virtual2.monitor sink=$Sink
else
    systemctl --user restart pulseaudio
fi
